# Generated by Django 3.1.2 on 2021-11-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_parser', '0002_auto_20210924_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': '<Буфер>',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='product',
            name='bank',
            field=models.TextField(default='', verbose_name='Банк'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.TextField(default='', verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='metall',
            field=models.TextField(default='', verbose_name='Металл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(default='', verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nb',
            field=models.TextField(default='', unique=True, verbose_name='Каталожный номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nominal',
            field=models.TextField(default=0, verbose_name='Номинал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.PositiveIntegerField(default=222, verbose_name='Год'),
            preserve_default=False,
        ),
    ]
