# Generated by Django 3.1.2 on 2021-12-18 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('av_parser', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Последний коммент'),
        ),
        migrations.AddField(
            model_name='comments',
            name='current_price',
            field=models.PositiveIntegerField(default=django.utils.timezone.now, verbose_name='Текущая цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='post_price',
            field=models.TextField(default='', verbose_name='Почтовый ценник'),
            preserve_default=False,
        ),
    ]
