# Generated by Django 3.1.2 on 2021-12-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('av_parser', '0007_auto_20211218_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='current_price',
        ),
    ]
