# Generated by Django 3.1.2 on 2021-12-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('av_parser', '0008_remove_comments_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post_price',
        ),
    ]
