# Generated by Django 3.1.2 on 2021-12-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_parser', '0012_remove_comments_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post1_price',
            field=models.CharField(default='', max_length=50, verbose_name='Почтовый ценник'),
            preserve_default=False,
        ),
    ]
