# Generated by Django 3.1.2 on 2021-12-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_parser', '0013_comments_post1_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='buy',
            field=models.TextField(default='No', verbose_name='Оплачено/Неоплачено'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='current_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущая цена'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='stack',
            field=models.PositiveIntegerField(default=0, verbose_name='Ставка'),
        ),
    ]
