# Generated by Django 3.1.2 on 2022-01-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_parser', '0014_auto_20211226_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='my_current_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Моя текущая цена'),
        ),
    ]
